POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbnJ5MyIsImlkIjoiNWZlYjNlMmMzOWE0NmY3ZDljZjc3NWNkIiwiaWF0IjoxNjA5MjUzMzg2fQ.Fzb4__d2RqlNvqi3G9TGo90zv1siabCgeSabrIkY4As

{
  "title": "Authorization BLOG 3333",
  "author": "Writer",
  "url": "www.blogurl.com",
  "likes": 11,
  "userId": "5feb2fd75c05f8784d0b2d8b"
}
