POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog 3",
  "author": "Writer",
  "url": "www.blogurl.com",
  "likes": 11,
  "userId": "5feb2fd75c05f8784d0b2d8b"
}
